spring:
  application:
    name: shopify-genie-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/shopify_genie
    username: postgres
    password: badsha@123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Shopify Configuration
shopify:
  api-version: 2024-01
  webhook-secret: ${SHOPIFY_WEBHOOK_SECRET:your-webhook-secret}
  client-id: ${SHOPIFY_CLIENT_ID:your-client-id}
  client-secret: ${SHOPIFY_CLIENT_SECRET:your-client-secret}
  scopes: read_products,write_products,read_orders,write_orders,read_customers,write_customers

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:5000  # Vite dev server
    - http://localhost:3000  # React dev server
    - http://localhost:5173  # Vite default port
    - http://127.0.0.1:5000
    - http://127.0.0.1:3000
    - http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: ShopifyGenie API
    description: Spring Boot backend for ShopifyGenie application
    version: 1.0.0
    contact:
      name: ShopifyGenie Team
      email: support@shopifygenie.com

# Logging Configuration
logging:
  level:
    com.shopifygenie: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
